### PR TITLE
Update phpseclib to ver 2.0.6

### PR DESCRIPTION
**Pull request by markkimsal**
This allows php7 to run without polluting the output with class constructor
warnings

### CODE REVIEW

**Comment by kohkimakimoto** [comment]
@markkimsal Thanks for your PR. But the travis-ci testing have failed.

```
Fatal error: Class 'Net_SFTP' not found in /home/travis/build/kohkimakimoto/altax/src/Altax/Module/Task/Process/Process.php 
```

Can you fix it?

**Comment by markkimsal** [comment]
coveralls:dev-master does not work with php-5.4 or php-5.3 anymore.

**Comment by markkimsal** [comment]
In order to support php5.3 and php5.4 someone needs to change composer.json to use coveralls 1.0.1 and run composer update and commit the composer.lock file as well as the composer.json file.  I tried, but after 20 minutes stopped composer.  All evidence points to php5.3 and 5.4 working, but getting travis to automatically prove this is not working at the moment.

**Comment by kohkimakimoto** [comment]
@markkimsal Now PHP5.3 and PHP5.4 are not supported versions in official PHP implementation. So we do not need to pass the tests for these versions in travis-ci.

Thank you so much for your help!

**Pull request merged**
